### ISSUE TITLE
T-rex speed issue

### ISSUE THREAD

**Issue by MrCreeps5000** [347956/JPOGTrex#10]
When the T-rex gets close to their target, it'll slow down significantly before actually reaching them. Even if the speed is set to be higher, the t-rex will still fail to kill the target unless they get stuck or otherwise stop moving.

https://github.com/user-attachments/assets/b61492f8-e4a6-44d0-b8d2-9f5f5ccf3d29

**Comment by 347956** [comment]
Thanks for pointing it out and providing a clip!
I'll look into it.
