### ISSUE TITLE
Death Delay

### ISSUE THREAD

**Issue by BBAPepsiMan** [347956/JPOGTrex#8]
After killing the clever girl, it walked in place for a second or two before finally falling over.

Also, just a suggestion, rename the entity itself from "JPOGTrex". Kind of looks a little silly, tbh.

**Comment by 347956** [comment]
I'll look into it.
Also didn't know the entity name was still "JPOGTrex", must have missed that. I'll fix that too.

Thanks for the feedback. 😎

**Comment by 347956** [comment]
Both should now be fixed.
