### ISSUE TITLE
Spawn Weight

### ISSUE THREAD

**Issue by BBAPepsiMan** [347956/JPOGTrex#9]
Hey! Mod works pretty much flawlessly now. All it needs now is spawn weight per moon as a config setting. This is less an issue and more a suggestion, but it'll get this beast spawning where pack makers want it.

Thanks again for fixing the previously stated issues.

**Comment by 347956** [comment]
I plan to implement this. Still looking how to and if I can get it to sync.
A bit busy now, but once I got some time I'll look into it.

**Comment by 347956** [comment]
Hey! It took a while for me to update/add the configurations. But it should work now I think.
